/// Flutter icons ISMIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ISMIcons
///      fonts:
///       - asset: fonts/ISMIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ISMIcons {
  ISMIcons._();

  static const _kFontFam = 'ism-icons';
  static const _kFontPkg = null;

  static IconData book = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData question_circle = IconData(0xf059, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData moon = IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
